name: CI

on:
  push:
    branches: ["**"]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Java 17 (Temurin)
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"
          cache: maven

      - name: Set up Google Chrome
        uses: browser-actions/setup-chrome@v1

      - name: Show Chrome version
        run: chrome --version || google-chrome --version || chromium --version

      - name: Run tests (headless)
        env:
          CI: "true"           # permet d'activer tes flags Chrome spéciaux en CI
        run: |
          mvn -B -Dheadless=true \
            -Dcucumber.plugin="pretty, summary, json:target/cucumber.json, html:target/cucumber-report.html" \
            test

      - name: List target (debug)
        if: always()
        run: ls -la target || true

      - name: Upload Cucumber reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: cucumber-reports
          path: |
            target/cucumber-report.html
            target/cucumber.json
          if-no-files-found: warn

      - name: Upload Surefire reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: surefire-reports
          path: target/surefire-reports/**
          if-no-files-found: warn
